language: node_js
node_js:
  - '10'

cache:
  yarn: true
  directories:
    - node_modules
    - dist/

env:
  global:
    - GITHUB_ORG="https://GH_TOKEN@github.com"
    - REPO_NAME="ng-nhl-team"
    - GITHUB_NAME="railsstudent"
    - GITHUB_EMAIL="cleung334@gmail.com"
    - DIST_DIR="dist/ng-nhl-team"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --pure-lockfile

script:
  - yarn audit
  - npm run lint
  - npm run build-ngh

after_success:
  - ngh --repo="$GITHUB_ORG/$GITHUB_NAME/$REPO_NAME.git" --name="$GITHUB_NAME" --email="$GITHUB_EMAIL" --dir="$DIST_DIR" --no-silent

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - '$GITHUB_EMAIL'
    on_success: never # default: change
    on_failure: always # default: always
